default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: favorite_books_development
  host: localhost
  port: 5432
  user: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: favorite_books_test
  host: localhost
  port: 5432
  user: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  
production:
  <<: *default
  database: favorite_books_production
  username: favorite_books
  password: <%= ENV['FAVORITE_BOOKS_DATABASE_PASSWORD'] %>
